# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_wasteschedule_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteschedule',
            name='status',
            field=models.CharField(
                choices=[
                    ('scheduled', 'Scheduled'),
                    ('continued', 'Continued'),
                    ('postponed', 'Postponed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='scheduled',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='wasteschedule',
            name='weather_recommendation',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wasteschedule',
            name='reschedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
