# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0001_initial'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherFetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_fetch_status', to='barangays.barangay')),
            ],
        ),
    ]
