# Generated by Codex on 2026-05-13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherfetchstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='weather.weatheralert'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='category',
            field=models.CharField(choices=[('weather', 'Weather'), ('schedule', 'Schedule')], default='weather', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(default='Wasto notification', max_length=255),
        ),
    ]
